import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';

import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { headers } from 'next/headers';

import ProgressBar from '@/components/ProgressBar';
import Header from '@/layouts/Header';

import Providers from './provider';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600'] });

export const metadata: Metadata = {
  title: 'NFT Launchpad',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = headers().get('cookie');
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <Providers cookie={cookie}>
          <ProgressBar />
          <Header />
          <main className='flex min-h-screen flex-col pb-16 pt-32 md:pb-8 md:pt-32'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
